name: upper-build-andres

on:
  push:
    paths:
      - ".github/workflows/upper-build-andres.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - run: go version
      